summon area_effect_cloud 0 1 0 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud 0 1 47 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud 47 1 47 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud 47 1 0 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud 47 1 -46 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud 0 1 -46 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud -46 1 -46 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud -46 1 0 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}
summon area_effect_cloud -46 1 47 {Particle:{type:"crimson_spore"},Radius:30f,Duration:10,potion_contents:{custom_color:16711680,custom_effects:[{id:"minecraft:instant_damage",amplifier:4,duration:20},{id:"minecraft:blindness",amplifier:4,duration:20}]},CustomName:'{"color":"red","text":"Dreadwrath"}'}

playsound minecraft:entity.lightning_bolt.impact master @a[tag=void] 0 0 0 999999 0
playsound minecraft:entity.lightning_bolt.thunder master @a[tag=void] 0 0 0 999999 0
playsound minecraft:entity.lightning_bolt.impact master @a[tag=void] 0 0 0 999999 2