
execute if score @s damIn matches 51 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 51","color":"red"}}
execute if score @s damIn matches 52 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 52","color":"red"}}
execute if score @s damIn matches 53 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 53","color":"red"}}
execute if score @s damIn matches 54 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 54","color":"red"}}
execute if score @s damIn matches 55 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 55","color":"red"}}
execute if score @s damIn matches 56 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 56","color":"red"}}
execute if score @s damIn matches 57 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 57","color":"red"}}
execute if score @s damIn matches 58 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 58","color":"red"}}
execute if score @s damIn matches 59 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 59","color":"red"}}
execute if score @s damIn matches 60 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 60","color":"red"}}
execute if score @s damIn matches 61 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 61","color":"red"}}
execute if score @s damIn matches 62 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 62","color":"red"}}
execute if score @s damIn matches 63 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 63","color":"red"}}
execute if score @s damIn matches 64 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 64","color":"red"}}
execute if score @s damIn matches 65 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 65","color":"red"}}
execute if score @s damIn matches 66 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 66","color":"red"}}
execute if score @s damIn matches 67 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 67","color":"red"}}
execute if score @s damIn matches 68 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 68","color":"red"}}
execute if score @s damIn matches 69 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 69","color":"red"}}
execute if score @s damIn matches 70 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 70","color":"red"}}
execute if score @s damIn matches 71 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 71","color":"red"}}
execute if score @s damIn matches 72 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 72","color":"red"}}
execute if score @s damIn matches 73 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 73","color":"red"}}
execute if score @s damIn matches 74 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 74","color":"red"}}
execute if score @s damIn matches 75 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 75","color":"red"}}
execute if score @s damIn matches 76 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 76","color":"red"}}
execute if score @s damIn matches 77 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 77","color":"red"}}
execute if score @s damIn matches 78 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 78","color":"red"}}
execute if score @s damIn matches 79 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 79","color":"red"}}
execute if score @s damIn matches 80 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 80","color":"red"}}
execute if score @s damIn matches 81 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 81","color":"red"}}
execute if score @s damIn matches 82 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 82","color":"red"}}
execute if score @s damIn matches 83 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 83","color":"red"}}
execute if score @s damIn matches 84 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 84","color":"red"}}
execute if score @s damIn matches 85 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 85","color":"red"}}
execute if score @s damIn matches 86 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 86","color":"red"}}
execute if score @s damIn matches 87 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 87","color":"red"}}
execute if score @s damIn matches 88 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 88","color":"red"}}
execute if score @s damIn matches 89 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 89","color":"red"}}
execute if score @s damIn matches 90 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 90","color":"red"}}
execute if score @s damIn matches 91 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 91","color":"red"}}
execute if score @s damIn matches 92 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 92","color":"red"}}
execute if score @s damIn matches 93 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 93","color":"red"}}
execute if score @s damIn matches 94 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 94","color":"red"}}
execute if score @s damIn matches 95 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 95","color":"red"}}
execute if score @s damIn matches 96 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 96","color":"red"}}
execute if score @s damIn matches 97 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 97","color":"red"}}
execute if score @s damIn matches 98 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 98","color":"red"}}
execute if score @s damIn matches 99 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 99","color":"red"}}
execute if score @s damIn matches 100 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 100","color":"red"}}
execute if score @s damIn matches 101.. as @s run function qol:datamergeextend3
