execute if score @s damIn matches 21 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 21","color":"red"}}
execute if score @s damIn matches 22 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 22","color":"red"}}
execute if score @s damIn matches 23 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 23","color":"red"}}
execute if score @s damIn matches 24 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 24","color":"red"}}
execute if score @s damIn matches 25 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 25","color":"red"}}
execute if score @s damIn matches 26 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 26","color":"red"}}
execute if score @s damIn matches 27 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 27","color":"red"}}
execute if score @s damIn matches 28 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 28","color":"red"}}
execute if score @s damIn matches 29 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 29","color":"red"}}
execute if score @s damIn matches 30 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 30","color":"red"}}
execute if score @s damIn matches 31 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 31","color":"red"}}
execute if score @s damIn matches 32 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 32","color":"red"}}
execute if score @s damIn matches 33 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 33","color":"red"}}
execute if score @s damIn matches 34 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 34","color":"red"}}
execute if score @s damIn matches 35 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 35","color":"red"}}
execute if score @s damIn matches 36 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 36","color":"red"}}
execute if score @s damIn matches 37 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 37","color":"red"}}
execute if score @s damIn matches 38 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 38","color":"red"}}
execute if score @s damIn matches 39 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 39","color":"red"}}
execute if score @s damIn matches 40 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 40","color":"red"}}
execute if score @s damIn matches 41 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 41","color":"red"}}
execute if score @s damIn matches 42 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 42","color":"red"}}
execute if score @s damIn matches 43 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 43","color":"red"}}
execute if score @s damIn matches 44 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 44","color":"red"}}
execute if score @s damIn matches 45 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 45","color":"red"}}
execute if score @s damIn matches 46 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 46","color":"red"}}
execute if score @s damIn matches 47 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 47","color":"red"}}
execute if score @s damIn matches 48 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 48","color":"red"}}
execute if score @s damIn matches 49 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 49","color":"red"}}
execute if score @s damIn matches 50 as @s on passengers run data merge entity @s {CustomName:{"text":"♥ 50","color":"red"}}
execute if score @s damIn matches 51.. as @s run function qol:datamergeextend2
