execute at @e[type=tnt,scores={fuse=80}] run summon area_effect_cloud ~ ~ ~ {Particle:{type:"flame"},CustomNameVisible:1b,Radius:0f,Duration:80,Tags:["tntDi"],CustomName:{"color":"red","text":"4.0"}}
execute as @e[type=area_effect_cloud,tag=tntDi] at @s run ride @s mount @e[type=tnt,sort=nearest,limit=1]
execute as @e[type=tnt,scores={fuse=78}] on passengers run data merge entity @s {CustomName:{"text":"3.9","color":"green"}}
execute as @e[type=tnt,scores={fuse=76}] on passengers run data merge entity @s {CustomName:{"text":"3.8","color":"green"}}
execute as @e[type=tnt,scores={fuse=74}] on passengers run data merge entity @s {CustomName:{"text":"3.7","color":"green"}}
execute as @e[type=tnt,scores={fuse=72}] on passengers run data merge entity @s {CustomName:{"text":"3.6","color":"green"}}
execute as @e[type=tnt,scores={fuse=70}] on passengers run data merge entity @s {CustomName:{"text":"3.5","color":"green"}}
execute as @e[type=tnt,scores={fuse=68}] on passengers run data merge entity @s {CustomName:{"text":"3.4","color":"green"}}
execute as @e[type=tnt,scores={fuse=66}] on passengers run data merge entity @s {CustomName:{"text":"3.3","color":"green"}}
execute as @e[type=tnt,scores={fuse=64}] on passengers run data merge entity @s {CustomName:{"text":"3.2","color":"green"}}
execute as @e[type=tnt,scores={fuse=62}] on passengers run data merge entity @s {CustomName:{"text":"3.1","color":"green"}}
execute as @e[type=tnt,scores={fuse=60}] on passengers run data merge entity @s {CustomName:{"text":"3.0","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=58}] on passengers run data merge entity @s {CustomName:{"text":"2.9","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=56}] on passengers run data merge entity @s {CustomName:{"text":"2.8","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=54}] on passengers run data merge entity @s {CustomName:{"text":"2.7","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=52}] on passengers run data merge entity @s {CustomName:{"text":"2.6","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=50}] on passengers run data merge entity @s {CustomName:{"text":"2.5","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=48}] on passengers run data merge entity @s {CustomName:{"text":"2.4","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=46}] on passengers run data merge entity @s {CustomName:{"text":"2.3","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=44}] on passengers run data merge entity @s {CustomName:{"text":"2.2","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=42}] on passengers run data merge entity @s {CustomName:{"text":"2.1","color":"yellow"}}
execute as @e[type=tnt,scores={fuse=40}] on passengers run data merge entity @s {CustomName:{"text":"2.0","color":"red"}}
execute as @e[type=tnt,scores={fuse=38}] on passengers run data merge entity @s {CustomName:{"text":"1.9","color":"red"}}
execute as @e[type=tnt,scores={fuse=36}] on passengers run data merge entity @s {CustomName:{"text":"1.8","color":"red"}}
execute as @e[type=tnt,scores={fuse=34}] on passengers run data merge entity @s {CustomName:{"text":"1.7","color":"red"}}
execute as @e[type=tnt,scores={fuse=32}] on passengers run data merge entity @s {CustomName:{"text":"1.6","color":"red"}}
execute as @e[type=tnt,scores={fuse=30}] on passengers run data merge entity @s {CustomName:{"text":"1.5","color":"red"}}
execute as @e[type=tnt,scores={fuse=28}] on passengers run data merge entity @s {CustomName:{"text":"1.4","color":"red"}}
execute as @e[type=tnt,scores={fuse=26}] on passengers run data merge entity @s {CustomName:{"text":"1.3","color":"red"}}
execute as @e[type=tnt,scores={fuse=24}] on passengers run data merge entity @s {CustomName:{"text":"1.2","color":"red"}}
execute as @e[type=tnt,scores={fuse=22}] on passengers run data merge entity @s {CustomName:{"text":"1.1","color":"red"}}
execute as @e[type=tnt,scores={fuse=20}] on passengers run data merge entity @s {CustomName:{"text":"1.0","color":"red"}}
execute as @e[type=tnt,scores={fuse=18}] on passengers run data merge entity @s {CustomName:{"text":"0.9","color":"red"}}
execute as @e[type=tnt,scores={fuse=16}] on passengers run data merge entity @s {CustomName:{"text":"0.8","color":"red"}}
execute as @e[type=tnt,scores={fuse=14}] on passengers run data merge entity @s {CustomName:{"text":"0.7","color":"red"}}
execute as @e[type=tnt,scores={fuse=12}] on passengers run data merge entity @s {CustomName:{"text":"0.6","color":"red"}}
execute as @e[type=tnt,scores={fuse=10}] on passengers run data merge entity @s {CustomName:{"text":"0.5","color":"red"}}
execute as @e[type=tnt,scores={fuse=8}] on passengers run data merge entity @s {CustomName:{"text":"0.4","color":"red"}}
execute as @e[type=tnt,scores={fuse=6}] on passengers run data merge entity @s {CustomName:{"text":"0.3","color":"red"}}
execute as @e[type=tnt,scores={fuse=4}] on passengers run data merge entity @s {CustomName:{"text":"0.2","color":"red"}}
execute as @e[type=tnt,scores={fuse=2}] on passengers run data merge entity @s {CustomName:{"text":"0.1","color":"red"}}